# Generated by Django 2.2.4 on 2019-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('FD', 'Food'), ('HE', 'Health'), ('MU', 'Meetups'), ('CK', 'Cooking')], default='TC', max_length=1),
            preserve_default=False,
        ),
    ]
