# Generated by Django 2.2.4 on 2019-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_pictures'),
        ),
    ]
