# Generated by Django 2.2.4 on 2019-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_main', '0002_auto_20190816_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TC', 'Technology'), ('FD', 'Food'), ('HE', 'Health'), ('MU', 'Meetups'), ('CK', 'Cooking')], default='TC', max_length=2),
            preserve_default=False,
        ),
    ]
