# Generated by Django 2.2.3 on 2019-08-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_main', '0005_auto_20190817_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
