# Generated by Django 2.2.4 on 2019-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_main', '0006_post_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpost',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
